from peewee import *

db = PostgresqlDatabase('elements', user='postgres', password='',host='localhost', port=5432)

db.connect()

class BaseModel(Model):
    class Meta:
        database = db
class Elements(BaseModel):
    name = CharField()
    abbreviation = CharField()

def flashcards():
    db.create_tables([Elements])
    card1 = Elements(name = 'Hydrogen', abbreviation = 'H')
    card2 = Elements(name = 'Helium', abbreviation = 'He')
    card3 = Elements(name = 'Lithium', abbreviation = 'Li')
    card4 = Elements(name = 'Beryllium', abbreviation = 'Be')
    card5 = Elements(name = 'Boron', abbreviation = 'B')
    card6 = Elements(name = 'Carbon', abbreviation = 'C')
    card7 = Elements(name = 'Nitrogen', abbreviation = 'N')
    card8 = Elements(name = 'Oxygen', abbreviation = 'O')
    card9 = Elements(name = 'Fluorine', abbreviation = 'F')
    card10 = Elements(name = 'Neon', abbreviation = 'N')
    card11 = Elements(name = 'Sodium', abbreviation = 'Na')
    card12 = Elements(name = 'Magnesium', abbreviation = 'Mg')
    card13 = Elements(name = 'Aluminum', abbreviation = 'Al')
    card14 = Elements(name = 'Silicon', abbreviation = 'Si')
    card15 = Elements(name = 'Phosphorus', abbreviation = 'P')
    card16 = Elements(name = 'Sulfur', abbreviation = 'S')
    card17 = Elements(name = 'Chlorine', abbreviation = 'Cl')
    card18 = Elements(name = 'Argon', abbreviation = 'Ar')
    card19 = Elements(name = 'Potassium', abbreviation = 'K')
    card20 = Elements(name = 'Calcium', abbreviation = 'Ca')
    card21 = Elements(name = 'Scandium', abbreviation = 'Sc')
    card22 = Elements(name = 'Titanium', abbreviation = 'Ti')
    card23 = Elements(name = 'Vanadium', abbreviation = 'V')
    card24 = Elements(name = 'Chromium', abbreviation = 'Cr')
    card25 = Elements(name = 'Manganese', abbreviation = 'Mn')
    card26 = Elements(name = 'Iron', abbreviation = 'Fe')
    card27 = Elements(name = 'Cobalt', abbreviation = 'Co')
    card28 = Elements(name = 'Nickel', abbreviation = 'Ni')
    card29 = Elements(name = 'Copper', abbreviation = 'Cu')
    card30 = Elements(name = 'Zinc', abbreviation = 'Zn')
    card31 = Elements(name = 'Gallium', abbreviation = 'Ga')
    card32 = Elements(name = 'Germanium', abbreviation = 'Ge')
    card33 = Elements(name = 'Arsenic', abbreviation = 'As')
    card34 = Elements(name = 'Selenium', abbreviation = 'Se')
    card35 = Elements(name = 'Bromine', abbreviation = 'Br')
    card36 = Elements(name = 'Krypton', abbreviation = 'Kr')
    card37 = Elements(name = 'Rubidium', abbreviation = 'Rb')
    card38 = Elements(name = 'Strontium', abbreviation = 'Sr')
    card39 = Elements(name = 'Yttrium', abbreviation = 'Y')
    card40 = Elements(name = 'Zirconium', abbreviation = 'Zr')
    card41 = Elements(name = 'Niobium', abbreviation = 'Nb')
    card42 = Elements(name = 'Molybdenum', abbreviation = 'Mo')
    card43 = Elements(name = 'Technetium', abbreviation = 'Tc')
    card44 = Elements(name = 'Ruthenium', abbreviation = 'Ru')
    card45 = Elements(name = 'Rhodium', abbreviation = 'Rh')
    card46 = Elements(name = 'Palladium', abbreviation = 'Pd')
    card47 = Elements(name = 'Silver', abbreviation = 'Ag')
    card48 = Elements(name = 'Cadmium', abbreviation = 'Cd')
    card49 = Elements(name = 'Indium', abbreviation = 'In')
    card50 = Elements(name = 'Tin', abbreviation = 'Sn')
    card51 = Elements(name = 'Antimony', abbreviation = 'Sb')
    card52 = Elements(name = 'Tellurium', abbreviation = 'Te')
    card53 = Elements(name = 'Iodine', abbreviation = 'I')
    card54 = Elements(name = 'Xenon', abbreviation = 'Xe')
    card55 = Elements(name = 'Cesium', abbreviation = 'Cs')
    card56 = Elements(name = 'Barium', abbreviation = 'Ba')
    card57 = Elements(name = 'Lanthanum', abbreviation = 'La')
    card58 = Elements(name = 'Cerium', abbreviation = 'Ce')
    card59 = Elements(name = 'Praseodymium', abbreviation = 'Pr')
    card60 = Elements(name = 'Neodymium', abbreviation = 'Nd')
    card61 = Elements(name = 'Promethium', abbreviation = 'Pm')
    card62 = Elements(name = 'Samarium', abbreviation = 'Sm')
    card63 = Elements(name = 'Europium', abbreviation = 'Eu')
    card64 = Elements(name = 'Gadolinium', abbreviation = 'Gd')
    card65 = Elements(name = 'Terbium', abbreviation = 'Tb')
    card66 = Elements(name = 'Dysprosium', abbreviation = 'Dy')
    card67 = Elements(name = 'Holmium', abbreviation = 'Ho')
    card68 = Elements(name = 'Erbium', abbreviation = 'Er')
    card69 = Elements(name = 'Thulium', abbreviation = 'Tm')
    card70 = Elements(name = 'Ytterbium', abbreviation = 'Yb')
    card71 = Elements(name = 'Lutetium', abbreviation = 'Lu')
    card72 = Elements(name = 'Hafnium', abbreviation = 'Hf')
    card73 = Elements(name = 'Tantalum', abbreviation = 'Ta')
    card74 = Elements(name = 'Tungsten', abbreviation = 'W')
    card75 = Elements(name = 'Rhenium', abbreviation = 'Re')
    card76 = Elements(name = 'Osmium', abbreviation = 'Os')
    card77 = Elements(name = 'Iridium', abbreviation = 'Ir')
    card78 = Elements(name = 'Platinum', abbreviation = 'Pt')
    card79 = Elements(name = 'Gold', abbreviation = 'Au')
    card80 = Elements(name = 'Mercury', abbreviation = 'Hg')
    card81 = Elements(name = 'Thallium', abbreviation = 'Tl')
    card82 = Elements(name = 'Lead', abbreviation = 'Pb')
    card83 = Elements(name = 'Bismuth', abbreviation = 'Bi')
    card84 = Elements(name = 'Polonium', abbreviation = 'Po')
    card85 = Elements(name = 'Astatine', abbreviation = 'At')
    card86 = Elements(name = 'Radon', abbreviation = 'Rn')
    card87 = Elements(name = 'Francium', abbreviation = 'Fr')
    card88 = Elements(name = 'Radium', abbreviation = 'Ra')
    card89 = Elements(name = 'Actinium', abbreviation = 'Ac')
    card90 = Elements(name = 'Thorium', abbreviation = 'Th')
    card91 = Elements(name = 'Protactinium', abbreviation = 'Pa')
    card92 = Elements(name = 'Uranium', abbreviation = 'U')
    card93 = Elements(name = 'Neptunium', abbreviation = 'Np')
    card94 = Elements(name = 'Plutonium', abbreviation = 'Pu')
    card95 = Elements(name = 'Americium', abbreviation = 'Am')
    card96 = Elements(name = 'Curium', abbreviation = 'Cm')
    card97 = Elements(name = 'Berkelium', abbreviation = 'Bk')
    card98 = Elements(name = 'Californium', abbreviation = 'Cf')
    card99 = Elements(name = 'Einsteinium', abbreviation = 'Es')
    card100 = Elements(name = 'Fermium', abbreviation = 'Fm')
    card101 = Elements(name = 'Mendelevium', abbreviation = 'Md')
    card102 = Elements(name = 'Nobelium', abbreviation = 'No')
    card103 = Elements(name = 'Lawrencium', abbreviation = 'Lr')
    card104 = Elements(name = 'Rutherfordium', abbreviation = 'Rf')
    card105 = Elements(name = 'Dubnium', abbreviation = 'Db')
    card106 = Elements(name = 'Seaborgium', abbreviation = 'Sg')
    card107 = Elements(name = 'Bohrium', abbreviation = 'Bh')
    card108 = Elements(name = 'Hassium', abbreviation = 'Hs')
    card109 = Elements(name = 'Meitnerium', abbreviation = 'Mt')
    card110 = Elements(name = 'Darmstadtium', abbreviation = 'Ds')
    card111 = Elements(name = 'Roentgenium', abbreviation = 'Rg')
    card112 = Elements(name = 'Ununbiium', abbreviation = 'Uub')
    card114 = Elements(name = 'Ununquadium', abbreviation = 'Uuq')



